### ISSUE TITLE
[CBS] issue 

### ISSUE THREAD

**Issue by 89z** [89z/mech#43]
https://www.cbs.com/shows/video/tXG2JqDwvC48qXgNikStaBAxMOd0wdl6/

**Comment by 89z** [comment]
Fixed:

~~~
PS C:\> paramount -i -b tXG2JqDwvC48qXgNikStaBAxMOd0wdl6
GET https://link.theplatform.com/s/dJ5BDC/media/guid/2198311517/tXG2JqDwvC48qXgNikStaBAxMOd0wdl6?format=SMIL&formats=MPEG4%2CM3U
GET https://cbsios-vh.akamaihd.net/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2022/03/29/2017594947995/TPIR_9792_ms_2CH_1268347_,503,4628,3128,2228,1628,848,000.mp4.csmil/master.m3u8?hdnea=acl=/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2022/03/29/2017594947995/TPIR_9792_ms_2CH_1268347_*~exp=1649207078~hmac=a0ecacf37d3af315fa20f375250ed13edd9e9b68fb161dda912e84230aa85074
The Price is Right - 4/5/2022
Resolution:1280x720 Bandwidth:3109000 Codecs:avc1.640028, mp4a.40.2
Resolution:1024x576 Bandwidth:2215000 Codecs:avc1.640028, mp4a.40.2
Resolution:960x540 Bandwidth:1617000 Codecs:avc1.640028, mp4a.40.2
Resolution:1920x1080 Bandwidth:4598000 Codecs:avc1.640028, mp4a.40.2
Resolution:768x432 Bandwidth:840000 Codecs:avc1.640028, mp4a.40.2
Resolution:640x360 Bandwidth:498000 Codecs:avc1.640028, mp4a.40.2
Bandwidth:96000 Codecs:mp4a.40.2
~~~

**Comment by 89z** [comment]
@TPIRFan

**Comment by TPIRFan** [comment]
I must be missing something obvious here -- I'm still getting the exact same error.  Is there something else I need to be doing or a different set of commands I need to be typing?

**Comment by 89z** [comment]
Sorry for the confusion. If youre interested, I have an alternate tool here:

https://github.com/89z/mech/releases/tag/v1.51.1

**Comment by TPIRFan** [comment]
I appreciate the offer, but I'd like to figure out what it is I'm doing wrong here.  I use YouTube-dl for this one specific thing that usually _just works,_ and I can see that you got it to run properly, so there's probably something I'm not doing that would seem obvious to anyone else.  Is there something other than YT-dl itself that I need to update?  Is there possibly a file I need that I don't currently have?  I have very little installed alongside it right now, and what I do have has been there so long that I don't remember _why_ I have it anymore.

**Comment by 89z** [comment]
Sorry I cant help you with that. You can you my tool if you like, or you can wait for a response on the YouTube-DL issue. Good luck.

**Comment by TPIRFan** [comment]
Actually, I take it back -- as always, it's something simple.  The new URLs _do_ continue to have a long version -- I was just creating it incorrectly.  Totally my fault.

Regardless, thanks for the assistance.

**Comment by Sipherdrakon** [comment]
@TPIRFan 
For now until youtube-dl is updated you can pull the long form versions of the URLs, I believe, from the /episodes list. So just take your show and add `/episodes` to the end and it should give you a list of seasons and all episodes available within that season.
ie, `https://www.paramountplus.com/shows/nick-cannon-presents-wild-n-out/episodes/`

**Comment by 89z** [comment]
@Simon818

~~~
PS C:\> paramount -i -b 3MlJs67tABl_TJTMzBSX3BXrtXULF8G2
GET https://link.theplatform.com/s/dJ5BDC/media/guid/2198311517/3MlJs67tABl_TJTMzBSX3BXrtXULF8G2?format=SMIL&formats=MPEG4%2CM3U
GET https://cbsios-vh.akamaihd.net/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2022/02/07/2000507459608/YOUNG_SHELDON_514_2398_1920x1080_1191185_,503,4628,3128,2228,1628,848,000.mp4.csmil/master.m3u8?hdnea=acl=/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2022/02/07/2000507459608/YOUNG_SHELDON_514_2398_1920x1080_1191185_*~exp=1649253801~hmac=148782d6a75c52e9b9a9f898826c1e33c0d3e4f1cd1b97ba00cac9fac5a54dbe
Young Sheldon - A Free Scratcher and Feminine Wiles
Resolution:1280x720 Bandwidth:3078000 Codecs:avc1.640028, mp4a.40.2
Resolution:1024x576 Bandwidth:2203000 Codecs:avc1.640028, mp4a.40.2
Resolution:960x540 Bandwidth:1610000 Codecs:avc1.640028, mp4a.40.2
Resolution:1920x1080 Bandwidth:4556000 Codecs:avc1.640028, mp4a.40.2
Resolution:768x432 Bandwidth:836000 Codecs:avc1.640028, mp4a.40.2
Resolution:640x360 Bandwidth:496000 Codecs:avc1.640028, mp4a.40.2
Bandwidth:93000 Codecs:mp4a.40.2
~~~

and:

~~~
PS C:\> paramount -i -b wrLAMWx4c7JoF_31bik2u_OfZrPfwIlh
GET https://link.theplatform.com/s/dJ5BDC/media/guid/2198311517/wrLAMWx4c7JoF_31bik2u_OfZrPfwIlh?format=SMIL&formats=MPEG4%2CM3U
GET https://cbsios-vh.akamaihd.net/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2022/01/13/1992546883655/YOUNG_SHELDON_513_2398_1920x1080_RRR_1155921_,503,4628,3128,2228,1628,848,000.mp4.csmil/master.m3u8?hdnea=acl=/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2022/01/13/1992546883655/YOUNG_SHELDON_513_2398_1920x1080_RRR_1155921_*~exp=1649253805~hmac=3b27735671c8483c75f03b9f464d3a621ff0b57b8a01f39c0f6d51b10013647d
Young Sheldon - A Lot of Band-Aids and the Cooper Surrender
Resolution:1280x720 Bandwidth:3078000 Codecs:avc1.640028, mp4a.40.2
Resolution:1024x576 Bandwidth:2198000 Codecs:avc1.640028, mp4a.40.2
Resolution:960x540 Bandwidth:1606000 Codecs:avc1.640028, mp4a.40.2
Resolution:1920x1080 Bandwidth:4548000 Codecs:avc1.640028, mp4a.40.2
Resolution:768x432 Bandwidth:836000 Codecs:avc1.640028, mp4a.40.2
Resolution:640x360 Bandwidth:496000 Codecs:avc1.640028, mp4a.40.2
Bandwidth:93000 Codecs:mp4a.40.2
~~~
